# Base image com suporte à interface de gerenciamento
FROM rabbitmq:3.13.7-management-alpine

# Definir variáveis de ambiente
ENV RABBITMQ_ERLANG_COOKIE=ED8MguofPhO3WR9d \
  RABBITMQ_DEFAULT_HOST=rabbitmq \
  RABBITMQ_DEFAULT_USER=LYRqzg1BvVNZxApO \
  RABBITMQ_DEFAULT_PASS=6CfHaOXaCbN62bH5 \
  TRAEFIK_ENABLE=true \
  TRAEFIK_HTTP_ROUTERS_RABBITMQ_RULE=Host\(`queues-nthb7.ondigitalocean.app`\) \
  TRAEFIK_HTTP_ROUTERS_RABBITMQ_ENTRYPOINTS=websecure \
  TRAEFIK_HTTP_ROUTERS_RABBITMQ_TLS_CERTRESOLVER=letsencryptresolver \
  TRAEFIK_HTTP_ROUTERS_RABBITMQ_SERVICE=rabbitmq \
  TRAEFIK_HTTP_SERVICES_RABBITMQ_LOADBALANCER_SERVER_PORT=15672 \
  TRAEFIK_HTTP_SERVICES_RABBITMQ_LOADBALANCER_PASSHOSTHEADER=true

# Expor portas padrão do RabbitMQ (5672 e 15672)
EXPOSE 5672 15672

# Comando padrão
CMD ["rabbitmq-server"]